# PrettyReMark -- Makefile (replaces rebuild.cmd)
#
# Wraps dotnet publish + Inno Setup for building, and glab for GitLab releases.
# VERSION is scraped from the most recent CHANGELOG.md entry and threaded through
# to Inno Setup via /D, so PrettyReMark.iss no longer needs its version hardcoded
# (see the #ifndef MyAppVersion block that needs adding there).
#
# AppVersion.cs is generated from VERSION by the "single" target below, so
# CHANGELOG.md is the single source of truth -- AppVersion.cs itself is
# build output and should not be hand-edited or committed with a stale value.

# Pull the most recent version out of CHANGELOG.md, e.g. "## [1.07]" -> 1.07
# Assumes the same "## [x.y]" header format used in the wbigcalc project --
# adjust the regex below if PrettyReMark's CHANGELOG.md differs.
VERSION := $(shell grep -oE '\[[0-9]+\.[0-9]+\]' CHANGELOG.md | head -n 1 | tr -d '[]')

SETUP_EXE = Output/PrettyReMarkV$(VERSION).setup.exe
SETUP_ZIP = Output/PrettyReMarkV$(VERSION).setup.zip
TAG        = v$(VERSION)

# Explicit -R avoids glab's "which is the base repository?" prompt, since this
# repo is a fork of eagle1's original and glab otherwise asks each time.
GLAB_REPO = DerellLicht/pretty-mark

.PHONY: single setup dist release update clean

# rebuild.cmd's "single" target -- stand-alone self-extracting exe.
# (The old "build" target -- loose-file publish -- is gone: PrettyReMark.iss
# only ever pulled the single exe out of publish\, never the loose-file layout,
# so there was nothing depending on it.)
#
# AppVersion.cs is regenerated from VERSION unconditionally, every build --
# not via a CHANGELOG.md-timestamp file target, since a fresh git checkout
# can land both files with the same timestamp and skip regeneration. This
# matches the "rm -rf bin obj" line right above it: single already does a
# full rebuild every time, so there's no benefit to being clever here.
single:
	rm -rf bin obj
	@printf 'namespace PrettyReMark;\n\n// Single source of truth for the application version. Shown in the About\n// dialog (via setAppVersion() in index.html). Generated by "make" from\n// CHANGELOG.md -- do not hand-edit, your changes will be overwritten.\nstatic class AppVersion\n{\n    public const string Current = "%s";\n}\n' "$(VERSION)" > AppVersion.cs
	dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true

# Compile the installer. VERSION is passed to Inno Setup on the command line
# instead of being hardcoded in PrettyReMark.iss. Depends on "single" so a bare
# "make setup" (or "make dist"/"release"/"update") always packages a fresh build.
setup: single
	rm -rf Output
	iscc /DMyAppVersion=$(VERSION) /Q PrettyReMark.iss

dist: setup
	zip -j $(SETUP_ZIP) $(SETUP_EXE)

# Tag, push, and publish a new GitLab release with the installer attached and
# release notes sliced out of the current CHANGELOG.md entry.
release: dist
	@echo Preparing GitLab release $(TAG)...
	sed -n '/## \[$(VERSION)\]/,/## \[/p' CHANGELOG.md | sed '$$d' > temp_notes.md
	git tag $(TAG)
	git push origin $(TAG)
	glab release create $(TAG) $(SETUP_ZIP) --notes-file temp_notes.md -R $(GLAB_REPO)
	rm temp_notes.md
	@echo Release $(TAG) uploaded to GitLab!

# Re-upload the installer to an existing release (e.g. after a rebuild), without
# re-tagging. NOTE: unlike "gh release upload", "glab release upload" has no
# --clobber flag -- untested whether it silently overwrites a same-named asset
# or errors out. Verify this before relying on it for a real re-upload.
update: dist
	@echo Updating assets for existing release $(TAG)...
	glab release upload $(TAG) $(SETUP_ZIP) -R $(GLAB_REPO)
	@echo Release $(TAG) assets updated on GitLab!

clean:
	rm -rf bin obj Output


# --- Static analysis / linting ------------------------------------------
# Four tools cover the whole codebase: Roslynator (C#), vnu.jar (the Nu Html
# Checker, for the WebView2 HTML), stylelint (CSS), and eslint (JS, pulled
# out of index.html via eslint-plugin-html). Each gets its own target so any
# one can be run standalone; "lint" runs all four and leaves each tool's raw
# output under reports\.
#
# These tools exit nonzero when they find issues, which is the normal/
# expected case, not a make failure. lint-cs is prefixed with "-" to keep
# going regardless (roslynator's own report makes the outcome clear either
# way). lint-html/css/js instead capture the exit status themselves, append
# an explicit "no issues found" / "issues found" line to their report, AND
# echo that same line to the console -- those three tools are silent on a
# clean run, and silent isn't just ambiguous, it also hides a genuine setup
# failure (missing config, missing plugin) behind what looks like a clean
# pass. This replaces the old lint-all.ps1, which existed only to work
# around make aborting on a nonzero exit.
#
# One-time setup (per machine, not per build):
#   - roslynator: dotnet tool install -g roslynator.dotnet.cli
#   - vnu.jar: download and point VNU_JAR below at it (shared tools\ folder,
#     not per-project -- see build_tools.md)
#   - node + npm install -g eslint eslint-plugin-html stylelint stylelint-config-standard
#   - .stylelintrc.json in this repo's root, extending stylelint-config-standard
#     (stylelint exits 78 immediately with no config file present)
#   - eslint.config.js in this repo's root registering eslint-plugin-html
#     for *.html -- under ESLint 9/10 flat config, a bare "--plugin html"
#     CLI flag does nothing (that only worked pre-flat-config); the plugin
#     has to be imported and registered in eslint.config.js itself. Both
#     files are provided alongside this Makefile -- drop them in the repo
#     root as-is.

VNU_JAR = ../tools/vnu.jar

.PHONY: lint lint-cs lint-html lint-css lint-js roslyn

lint: lint-cs lint-html lint-css lint-js
	@echo Lint reports written to reports\

reports:
	mkdir -p reports

lint-cs: | reports
	-roslynator analyze PrettyReMark.csproj --output reports/csharp.xml --verbosity normal

lint-html: | reports
	@java -jar $(VNU_JAR) assets/index.html > reports/html.txt 2>&1; \
	status=$$?; \
	if [ $$status -eq 0 ]; then \
		msg="vnu.jar: no issues found"; \
	else \
		msg="vnu.jar: issues found (exit $$status) -- see reports/html.txt"; \
	fi; \
	echo "$$msg" >> reports/html.txt; \
	echo "$$msg"

lint-css: | reports
	@stylelint --no-color assets/*.css > reports/css.txt 2>&1; \
	status=$$?; \
	if [ $$status -eq 0 ]; then \
		msg="stylelint: no issues found"; \
	else \
		msg="stylelint: issues found (exit $$status) -- see reports/css.txt"; \
	fi; \
	echo "$$msg" >> reports/css.txt; \
	echo "$$msg"

lint-js: | reports
	@eslint --no-color assets/index.html > reports/js.txt 2>&1; \
	status=$$?; \
	if [ $$status -eq 0 ]; then \
		msg="eslint: no issues found"; \
	else \
		msg="eslint: issues found (exit $$status) -- see reports/js.txt"; \
	fi; \
	echo "$$msg" >> reports/js.txt; \
	echo "$$msg"