# PrettyReMark -- Makefile (replaces rebuild.cmd)
#
# Wraps dotnet publish + Inno Setup for building, and glab for GitLab releases.
# VERSION is scraped from the most recent CHANGELOG.md entry and threaded through
# to Inno Setup via /D, so PrettyReMark.iss no longer needs its version hardcoded
# (see the #ifndef MyAppVersion block that needs adding there).
#
# AppVersion.cs is generated from VERSION by the "single" target below, so
# CHANGELOG.md is the single source of truth -- AppVersion.cs itself is
# build output and should not be hand-edited or committed with a stale value.

# Pull the most recent version out of CHANGELOG.md, e.g. "## [1.07]" -> 1.07
# Assumes the same "## [x.y]" header format used in the wbigcalc project --
# adjust the regex below if PrettyReMark's CHANGELOG.md differs.
VERSION := $(shell grep -oE '\[[0-9]+\.[0-9]+\]' CHANGELOG.md | head -n 1 | tr -d '[]')

SETUP_EXE = Output/PrettyReMarkV$(VERSION).setup.exe
SETUP_ZIP = Output/PrettyReMarkV$(VERSION).setup.zip
TAG        = v$(VERSION)

# Explicit -R avoids glab's "which is the base repository?" prompt, since this
# repo is a fork of eagle1's original and glab otherwise asks each time.
GLAB_REPO = DerellLicht/pretty-mark

# GLAB_REPO with the "/" percent-encoded, for use as the :id in "glab api"
# path segments (e.g. projects/<GLAB_REPO_ENC>/releases/...) -- glab api
# doesn't accept a bare "owner/repo" there the way -R does elsewhere.
GLAB_REPO_ENC = $(subst /,%2F,$(GLAB_REPO))

.PHONY: single setup dist release update retag re-release check-clean clean install

# rebuild.cmd's "single" target -- stand-alone self-extracting exe.
# (The old "build" target -- loose-file publish -- is gone: PrettyReMark.iss
# only ever pulled the single exe out of publish\, never the loose-file layout,
# so there was nothing depending on it.)
#
# AppVersion.cs is regenerated from VERSION unconditionally, every build --
# not via a CHANGELOG.md-timestamp file target, since a fresh git checkout
# can land both files with the same timestamp and skip regeneration. This
# matches the "rm -rf bin obj" line right above it: single already does a
# full rebuild every time, so there's no benefit to being clever here.
single:
	rm -rf bin obj
	@printf 'namespace PrettyReMark;\n\n// Single source of truth for the application version. Shown in the About\n// dialog (via setAppVersion() in index.html). Generated by "make" from\n// CHANGELOG.md -- do not hand-edit, your changes will be overwritten.\nstatic class AppVersion\n{\n    public const string Current = "%s";\n}\n' "$(VERSION)" > AppVersion.cs
	dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true

# Compile the installer. VERSION is passed to Inno Setup on the command line
# instead of being hardcoded in PrettyReMark.iss. Depends on "single" so a bare
# "make setup" (or "make dist"/"release"/"update") always packages a fresh build.
setup: single
	rm -rf Output
	iscc /DMyAppVersion=$(VERSION) /Q PrettyReMark.iss

dist: setup
	zip -j $(SETUP_ZIP) $(SETUP_EXE)

# Refuses to proceed if the working tree has uncommitted or untracked changes
# -- the exact mistake that prompted this target: a release built from a
# working tree that doesn't match what "git tag" is about to point at.
# A prerequisite of "release" and "retag" (not "dist"/"setup"/"single" --
# those are also used standalone for local testing, where an uncommitted
# tree is completely normal) so it runs, and can fail, BEFORE the expensive
# rebuild -- "release: check-clean dist" checks first, builds second.
check-clean:
	@if [ -n "$$(git status --porcelain)" ]; then \
		echo "ERROR: uncommitted changes present -- commit before releasing."; \
		git status --short; \
		exit 1; \
	fi

# Tag, push, and publish a new GitLab release with the installer attached and
# release notes sliced out of the current CHANGELOG.md entry.
release: check-clean dist
	@echo Preparing GitLab release $(TAG)...
	sed -n '/## \[$(VERSION)\]/,/## \[/p' CHANGELOG.md | sed '$$d' > temp_notes.md
	git tag $(TAG)
	git push origin $(TAG)
	glab release create $(TAG) $(SETUP_ZIP) --notes-file temp_notes.md -R $(GLAB_REPO)
	rm temp_notes.md
	@echo Release $(TAG) uploaded to GitLab!

# Re-upload the installer to an existing release (e.g. after a rebuild), without
# re-tagging. Only correct when $(TAG) already points at the commit you actually
# want released -- e.g. a flaky build, or you deleted Output\ and need to
# regenerate/reattach the same artifact. If the source has changed since the
# tag was created, use "re-release" below instead -- this target will happily
# upload a binary that no longer matches what git says $(TAG) is.
#
# NOTE: unlike "gh release upload", "glab release upload" has no --clobber
# flag -- CONFIRMED (2026-09) it does NOT overwrite a same-named asset, it
# errors: "Name has already been taken, Filepath has already been taken."
# This bites every time this target is re-run against a version whose
# assets were already uploaded once -- the "do a release, then immediately
# spot something to fix" case -- since a link with that name already
# exists on $(TAG). glab has no per-asset delete subcommand (only
# "glab release delete <tag>", which removes the whole release), so
# instead this target looks up any existing link matching this build's
# filename via "glab api" and deletes it first, before uploading. That
# makes "update" (and therefore "re-release") idempotent -- safe to run
# as many times as needed against the same tag. Requires jq (winget
# install jqlang.jq) to pick the matching link's id out of the
# link-listing JSON. The "tr -d '\r'" is required because "glab api" is a
# native Windows binary and emits CRLF line endings; $(...) command
# substitution only strips the capture's *trailing* newline, not the \r
# embedded before each internal line, so without this each $$id comes out
# as e.g. "13074777\r" and glab's own request-building chokes on the
# stray \r in the URL ("invalid control character in URL").
#
# Also re-slices CHANGELOG.md and pushes it as the release notes, same as
# "release" does on first publish. Without this, editing CHANGELOG.md's
# current-version section AFTER the initial "release" (the "one more
# thing" case this whole target exists for) would leave GitLab's notes
# field stale forever, even though the committed CHANGELOG.md is current
# -- "update" would fix the binary but silently leave the notes behind.
# There's no separate "glab release update" subcommand; "glab release
# create" doubles as update when the tag already exists (confirmed via
# glab's own docs: "Create a new GitLab release ... or update an existing
# one"), touching only what's passed -- so calling it again with just
# --notes-file, no asset argument, updates notes without disturbing the
# asset link just uploaded above.
update: dist
	@echo Updating assets for existing release $(TAG)...
	@for id in $$(glab api "projects/$(GLAB_REPO_ENC)/releases/$(TAG)/assets/links" \
	    | jq -r '.[] | select(.name=="$(notdir $(SETUP_ZIP))") | .id' | tr -d '\r'); do \
		echo Removing stale asset link $$id for $(notdir $(SETUP_ZIP))...; \
		glab api -X DELETE "projects/$(GLAB_REPO_ENC)/releases/$(TAG)/assets/links/$$id" >/dev/null; \
	done
	glab release upload $(TAG) $(SETUP_ZIP) -R $(GLAB_REPO)
	sed -n '/## \[$(VERSION)\]/,/## \[/p' CHANGELOG.md | sed '$$d' > temp_notes.md
	glab release create $(TAG) --notes-file temp_notes.md -R $(GLAB_REPO)
	rm temp_notes.md
	@echo Release $(TAG) assets and notes updated on GitLab!

# Recovery for "I ran release, then realized uncommitted changes were left
# out" -- force-moves $(TAG) to the current commit and force-pushes that
# move, then rebuilds and re-uploads via "update" so the release's binary
# matches where the tag now points. Safe for a solo repo (nobody else has
# based work on the old tag position); on a shared repo, force-pushing a
# moved tag out from under a collaborator who already fetched it is the
# kind of thing worth a heads-up first.
#
# Deliberately separate from "release" itself, which still uses a bare
# "git tag" (no -f) as a guard rail -- re-running "release" on an
# already-tagged version should fail loudly, not silently move the tag.
# Reach for "retag"/"re-release" only when you actually mean to. Also
# depends on check-clean, for the same reason "release" does -- retagging
# onto a dirty tree just relocates the exact mistake this is meant to fix.
retag: check-clean
	git tag -f $(TAG)
	git push origin $(TAG) --force

re-release: retag update
	@echo Release $(TAG) retagged and re-released.

clean:
	rm -rf bin obj Output

# new target for silent install from base folder
install:
	$(SETUP_EXE) /SILENT /SUPPRESSMSGBOXES /NORESTART
	
sha256:
	certutil -hashfile $(SETUP_ZIP) SHA256

# --- Static analysis / linting ------------------------------------------
# Four tools cover the whole codebase: Roslynator (C#), vnu.jar (the Nu Html
# Checker, for the WebView2 HTML), stylelint (CSS), and eslint (JS, pulled
# out of index.html via eslint-plugin-html). Each gets its own target so any
# one can be run standalone; "lint" runs all four and leaves each tool's raw
# output under reports\.
#
# These tools exit nonzero when they find issues, which is the normal/
# expected case, not a make failure. lint-cs is prefixed with "-" to keep
# going regardless (roslynator's own report makes the outcome clear either
# way). lint-html/css/js instead capture the exit status themselves, append
# an explicit "no issues found" / "issues found" line to their report, AND
# echo that same line to the console -- those three tools are silent on a
# clean run, and silent isn't just ambiguous, it also hides a genuine setup
# failure (missing config, missing plugin) behind what looks like a clean
# pass. This replaces the old lint-all.ps1, which existed only to work
# around make aborting on a nonzero exit.
#
# One-time setup (per machine, not per build):
#   - roslynator: dotnet tool install -g roslynator.dotnet.cli
#   - vnu.jar: download and point VNU_JAR below at it (shared tools\ folder,
#     not per-project -- see build_tools.md)
#   - node + npm install -g eslint eslint-plugin-html stylelint stylelint-config-standard
#   - .stylelintrc.json in this repo's root, extending stylelint-config-standard
#     (stylelint exits 78 immediately with no config file present)
#   - eslint.config.js in this repo's root registering eslint-plugin-html
#     for *.html -- under ESLint 9/10 flat config, a bare "--plugin html"
#     CLI flag does nothing (that only worked pre-flat-config); the plugin
#     has to be imported and registered in eslint.config.js itself. Both
#     files are provided alongside this Makefile -- drop them in the repo
#     root as-is.

VNU_JAR = ../tools/vnu.jar

.PHONY: lint lint-cs lint-html lint-css lint-js roslyn

lint: lint-cs lint-html lint-css lint-js
	@echo Lint reports written to reports\

reports:
	mkdir -p reports

lint-cs: | reports
	-roslynator analyze PrettyReMark.csproj --output reports/csharp.xml --verbosity normal

lint-html: | reports
	@java -jar $(VNU_JAR) assets/index.html > reports/html.txt 2>&1; \
	status=$$?; \
	if [ $$status -eq 0 ]; then \
		msg="vnu.jar: no issues found"; \
	else \
		msg="vnu.jar: issues found (exit $$status) -- see reports/html.txt"; \
	fi; \
	echo "$$msg" >> reports/html.txt; \
	echo "$$msg"

lint-css: | reports
	@stylelint --no-color assets/*.css > reports/css.txt 2>&1; \
	status=$$?; \
	if [ $$status -eq 0 ]; then \
		msg="stylelint: no issues found"; \
	else \
		msg="stylelint: issues found (exit $$status) -- see reports/css.txt"; \
	fi; \
	echo "$$msg" >> reports/css.txt; \
	echo "$$msg"

lint-js: | reports
	@eslint --no-color assets/index.html > reports/js.txt 2>&1; \
	status=$$?; \
	if [ $$status -eq 0 ]; then \
		msg="eslint: no issues found"; \
	else \
		msg="eslint: issues found (exit $$status) -- see reports/js.txt"; \
	fi; \
	echo "$$msg" >> reports/js.txt; \
	echo "$$msg"