; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.

#define MyAppName "PrettyReMark"
#ifndef MyAppVersion
#define MyAppVersion "1.07"
#endif
#define MyAppPublisher "Derell Licht"
#define MyAppURL "https://derelllicht.42web.io/PrettyReMark.html"
#define MyAppExeName "PrettyReMark.exe"
#define DoubleAmp(Value) StringChange(Value, "&", "&&")
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")
#define RepoRoot "D:\SourceCode\Git\PrettyReMark"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{CFBE2C4D-7CAB-4E26-A6A2-321BBBB32455}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={cm:NameAndVersion,{#EscapeConstArgument(MyAppName)},{#EscapeConstArgument(MyAppVersion)}}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
; {autopf} resolves to the per-user Program Files equivalent
; (%LocalAppData%\Programs) since PrivilegesRequired=lowest below means this
; never runs elevated -- no hardcoded drive letter, no UAC prompt, and it
; matches the per-user install PrivilegesRequired=lowest already declares.
; (If PrivilegesRequired is ever changed to "admin", {autopf} would instead
; resolve to the real Program Files under HKLM, with no change needed here.)
DefaultDirName={autopf}\{#MyAppName}
; Explicit rather than relying on the "auto" default, so the destination
; picker always shows for an interactive install regardless of how Inno's
; heuristic reads DefaultDirName. Has no effect on /SILENT or /VERYSILENT --
; Inno skips every wizard page unattended either way, so this stays
; compliant with winget's "no interaction required" policy.
DisableDirPage=no
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.
; This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DefaultGroupName={#MyAppName}
LicenseFile={#RepoRoot}\LICENSE.MIT.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
PrivilegesRequired=lowest
OutputBaseFilename={#MyAppName}V{#MyAppVersion}.setup
SolidCompression=yes
WizardStyle=modern slate
; Lets the uninstaller warn about / clean up the file association added below.
ChangesAssociations=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "associatemd"; Description: "Associate .md files with {#MyAppName}"; GroupDescription: "File associations:"

[Files]
Source: "{#RepoRoot}\bin\Release\net8.0-windows\win-x64\publish\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#RepoRoot}\CHANGELOG.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#RepoRoot}\LICENSE.MIT.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#RepoRoot}\README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#RepoRoot}\assets\favicon.ico"; DestDir: "{app}\assets"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\assets\favicon.ico"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{group}\Changelog"; Filename: "{app}\CHANGELOG.md"
Name: "{group}\License"; Filename: "{app}\LICENSE.MIT.txt"
Name: "{group}\Readme"; Filename: "{app}\README.md"

[Run]
; This runs the INSTALLED app (post-install "Launch program now" checkbox) --
; it has nothing to do with the installer's own filename, so it must reference
; {#MyAppExeName} (the #define'd app exe), not OutputBaseFilename.
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#DoubleAmp(MyAppName)}}"; Flags: nowait postinstall skipifsilent

[Registry]
; HKA auto-resolves to HKCU\Software\Classes (matches PrivilegesRequired=lowest,
; a per-user install) or HKLM\Software\Classes for an admin install -- no need to
; hardcode which. Only touches .md; .txt is left alone since that's yours already.
Root: HKA; Subkey: "Software\Classes\.md"; ValueType: string; ValueName: ""; ValueData: "PrettyReMark.md"; Flags: uninsdeletevalue; Tasks: associatemd
Root: HKA; Subkey: "Software\Classes\PrettyReMark.md"; ValueType: string; ValueName: ""; ValueData: "Markdown Document"; Flags: uninsdeletekey; Tasks: associatemd
Root: HKA; Subkey: "Software\Classes\PrettyReMark.md\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"; Tasks: associatemd
Root: HKA; Subkey: "Software\Classes\PrettyReMark.md\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; Tasks: associatemd

[Code]
// SHChangeNotify tells Explorer to re-read file associations/icons immediately,
// instead of leaving the .md icon/association stale until next logon.
procedure SHChangeNotify(wEventId: Integer; uFlags: Integer; dwItem1: Integer; dwItem2: Integer);
  external 'SHChangeNotify@shell32.dll stdcall';

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
    SHChangeNotify($8000000, $1000, 0, 0); // SHCNE_ASSOCCHANGED, SHCNF_IDLIST
end;

